### ISSUE TITLE
Rain data does not match WLL records

### ISSUE THREAD

**Issue by selectSt4r** [michael-slx/weewx-weatherlink-live#7] opened 2021-03-21 17:44 UTC
The rain totals from WLL do not match what is captured by the driver.  The driver, if it doesn't match, is always slightly lower than what WLL reports.

![Screenshot 2021-03-21 121447](https://user-images.githubusercontent.com/32106123/111915226-872d3800-8a4b-11eb-9c7d-0c9efbb620c5.jpg)
![Screenshot 2021-03-21 121341](https://user-images.githubusercontent.com/32106123/111915227-87c5ce80-8a4b-11eb-84b0-6416259d0f6f.jpg)

**Comment by selectSt4r** [comment] 2021-03-21 17:46
The top screenshot, 11 rows down, is where 11MAR, and corresponds to the WeeWx Day 11.

**Comment by selectSt4r** [comment] 2021-03-30 13:20
After some investigation, I believe there are a couple issues at play.  First, some rainfall is not being archived.  It's usually just of by 0.01" or near that amount.  Next, if it's raining during the start of a new day, the rainfall amounts appear to be inaccurate.  It seems that the driver (or WeeWx, maybe) is unable to discern where (i.e., to which day) to allocate the rain amount archive values.  I will provide more information when I have time.

**Comment by michael-slx** [comment] 2021-04-02 11:49
Can you confirm that this only happens when it rains at midnight? A log with the debug output enabled would be helpful, if possible during midnight when the issue happens.

**Comment by selectSt4r** [comment] 2021-05-22 23:59
Attached is a file showing rain data from 09-MAY-2021.  I don't have logs.  I will have to wait until a good rain is in the forecast and then I will enable some debug-level logging.  I extracted data from WLL and joined it to WeeWX produced data.  If the Rain amount value for either data source was greater than zero, I returned the record.  I have two columns that indicate if there are mismatches between Rain Total and Rain Rate values for a timestamp.


[rainDataMismatches.xlsx](https://github.com/michael-slx/weewx-weatherlink-live/files/6527331/rainDataMismatches.xlsx)

**Comment by michael-slx** [comment] 2021-05-23 09:06
OK, thanks for the spreadsheet.

It seems that for those rows where the data doesn't match, the amount is always `0` and the rate is half the WLL's value. I've experienced a similar issue on my end, but it hasn't occurred since I've enabled the debug log either. It seems there is a crash that causes the driver to skip a packet.

For me, the rain amount field at the time of the crash was `NULL`. Can you check in your db if it's the same on your end?

**Comment by selectSt4r** [comment] 2021-05-23 13:14
Good observation on the ratio for the rain rate.  Didn't notice that.  Are you saying that the raw sensor data that you're retrieving from WLL is written somewhere in the DB?  The most granular table that I could see was the weewx.archive.

**Comment by michael-slx** [comment] 2021-05-23 13:19
No, I'm talking about the `weewx.archive` table. I'm asking because in my case the rain amount was actually `NULL` but got converted to `0` while exporting data to a CSV.

**Comment by selectSt4r** [comment] 2021-05-23 16:34
Just checked and they're `0` in the DB, not `NULL`.  I'm using WeeWX 4.5.1.

**Comment by michael-slx** [comment] 2021-05-23 17:20
OK, thanks. I'll continue to look into this.

**Comment by selectSt4r** [comment] 2021-06-01 18:40
Michael -- I have a good day of rain ahead of me.  Besides setting the logging to verbose in WeeWX, was there any other logging you need me to enable?

**Comment by michael-slx** [comment] 2021-06-01 18:45
That should be fine. Just set `debug = 1`, `log_success = True` and `log_failure = 1`.

**Comment by selectSt4r** [comment] 2021-06-01 19:11
Logging is set per your request.  FYI, log_failure is boolean like log_success.

**Comment by michael-slx** [comment] 2021-06-06 13:15
Hi @selectSt4r,

I've just published a new [development release](https://github.com/michael-slx/weewx-weatherlink-live/releases/tag/SNAPSHOT-2021-06-06) with some added log messages with regard to the UDP protocol.

Could you please run this version with debug logging on your end and send me a log dump? It doesn't matter whether or not there actually is any rain, I'm just interested in how the driver behaves on your end.

Specifically, I've added a log message showing how many bytes were received from what address.

**Comment by selectSt4r** [comment] 2021-06-07 01:46
Michael -- I've updated the extension to that dev release.  I'm logging with debug = 1.  BTW, the last two rainfalls -- no issues with the data.  Of course not :)  It rained off and on for at least 24 hours, and the rainfall total matched btw WLL and the extension.  Since it matched, I didn't get into the weeds of checking the 5-minute summary data btw the data sources.  How many mins/hours of log data do you want?

**Comment by selectSt4r** [comment] 2021-06-11 16:06
[selectSt4r_20210611.txt](https://github.com/michael-slx/weewx-weatherlink-live/files/6639727/selectSt4r_20210611.txt)
Michael -- this debug log file was generated using Snapshot 2021-06-06.

**Comment by selectSt4r** [comment] 2021-06-21 01:46
Rain data has been accurate for the last few rainstorms (using Snapshot 2021-06-06).  I will continue to observe now that I've just updated to v1.0.7.

**Comment by LMSSonos** [comment] 2021-08-27 15:00
@selectSt4r I have the same errors as you have in my log (result no rain info) with version 1.0.10

your log
```
Jun 11 00:00:11 weatherlinkpi weewx[7419] DEBUG user.weatherlink_live.mappers: RainMapping[['1']]: Mapping not responsible: Not a broadcast packet
Jun 11 00:00:11 weatherlinkpi weewx[7419] DEBUG user.weatherlink_live.mappers: WindMapping[['1']]: Mapping not responsible: Not a broadcast packet
```

my log
```
Aug 27 16:49:18 weewx[19] DEBUG user.weatherlink_live.mappers: RainMapping[['7']]: Mapping not responsible: Not a broadcast packet
Aug 27 16:49:18 weewx[19] DEBUG user.weatherlink_live.mappers: WindMapping[['7']]: Mapping not responsible: Not a broadcast packet
```

I tried to use the snapshot but when using that I get following issue

```
192.168.1.2Aug 27 16:58:10 weewx[19] DEBUG user.weatherlink_live.configuration: Creating mapper battery. Options: ['7', 'outTemp', 'rain', 'wind', 'uv']
192.168.1.2Aug 27 16:58:10 weewx[19] ERROR weewx.engine: Import of driver failed: name 'mapper_type' is not defined (<class 'NameError'>)
192.168.1.2Aug 27 16:58:10 weewx[19] CRITICAL weewx.engine:     ****  Traceback (most recent call last):
192.168.1.2Aug 27 16:58:10 weewx[19] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/weatherlink_live/configuration.py", line 103, in _create_mapper
192.168.1.2Aug 27 16:58:10 weewx[19] CRITICAL weewx.engine:     ****      mapper_init = MAPPERS[type]
192.168.1.2Aug 27 16:58:10 weewx[19] CRITICAL weewx.engine:     ****  KeyError: 'battery'
192.168.1.2Aug 27 16:58:10 weewx[19] CRITICAL weewx.engine:     ****
192.168.1.2Aug 27 16:58:10 weewx[19] CRITICAL weewx.engine:     ****  During handling of the above exception, another exception occurred:
192.168.1.2Aug 27 16:58:10 weewx[19] CRITICAL weewx.engine:     ****
192.168.1.2Aug 27 16:58:10 weewx[19] CRITICAL weewx.engine:     ****  Traceback (most recent call last):
192.168.1.2Aug 27 16:58:10 weewx[19] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/weewx/engine.py", line 119, in setupStation
192.168.1.2Aug 27 16:58:10 weewx[19] CRITICAL weewx.engine:     ****      self.console = loader_function(config_dict, self)
192.168.1.2Aug 27 16:58:10 weewx[19] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/weatherlink_live/__init__.py", line 100, in loader
192.168.1.2Aug 27 16:58:10 weewx[19] CRITICAL weewx.engine:     ****      return WeatherlinkLiveDriver(config_dict, engine)
192.168.1.2Aug 27 16:58:10 weewx[19] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/weatherlink_live/__init__.py", line 121, in __init__
192.168.1.2Aug 27 16:58:10 weewx[19] CRITICAL weewx.engine:     ****      self.mappers = self.configuration.create_mappers()
192.168.1.2Aug 27 16:58:10 weewx[19] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/weatherlink_live/configuration.py", line 94, in create_mappers
192.168.1.2Aug 27 16:58:10 weewx[19] CRITICAL weewx.engine:     ****      return [self._create_mapper(source_opts, used_record_keys) for source_opts in self.mappings]
192.168.1.2Aug 27 16:58:10 weewx[19] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/weatherlink_live/configuration.py", line 94, in <listcomp>
192.168.1.2Aug 27 16:58:10 weewx[19] CRITICAL weewx.engine:     ****      return [self._create_mapper(source_opts, used_record_keys) for source_opts in self.mappings]
192.168.1.2Aug 27 16:58:10 weewx[19] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/weatherlink_live/configuration.py", line 105, in _create_mapper
192.168.1.2Aug 27 16:58:10 weewx[19] CRITICAL weewx.engine:     ****      raise KeyError("Unknown mapper type: %s" % repr(mapper_type)) from e
192.168.1.2Aug 27 16:58:10 weewx[19] CRITICAL weewx.engine:     ****  NameError: name 'mapper_type' is not defined
192.168.1.2Aug 27 16:58:10 weewx[19] CRITICAL __main__: Unable to load driver: name 'mapper_type' is not defined
192.168.1.2Aug 27 16:58:10 weewx[19] CRITICAL __main__:     ****  Exiting...
```

did you change anything in your config?

**Comment by selectSt4r** [comment] 2021-08-28 17:27
I did not change anything in my config.  I am currently running v1.0.7 of the extension.  I will try upgrading.  Here is my specific config:

`[WeatherLinkLive]
    driver = user.weatherlink_live
    host = <IP address of host>
    polling_interval = 10
    mapping = th:1, th_indoor, baro, rain:1, wind:1, solar:1, uv:1, thw:1, thsw:1, windchill:1`

**Comment by LMSSonos** [comment] 2021-08-30 06:26
I changed now my config from

`mapping = th:7, th_indoor, baro, rain:7, wind:7, uv:7, solar:7, thw:7, thsw:7:appTemp, windchill:7, battery:7:outTemp:rain:wind:uv`

to 
`mapping = th:7, th_indoor, baro, rain:7, wind:7, uv:7, solar:7, thw:7, thsw:7:appTemp, windchill:7`

now the battery related error has gone, now I only have this one left ;-) I'm using v1.0.10

```
Aug 30 08:22:59 weewx[19] CRITICAL user.rtgd: Unexpected exception of type <class 'TypeError'>
Aug 30 08:22:59 weewx[19] DEBUG user.rtgd: rtgdthread: **** Traceback (most recent call last):
Aug 30 08:22:59 weewx[19] DEBUG user.rtgd: rtgdthread: ****   File "/home/weewx/bin/user/rtgd.py", line 1750, in run
Aug 30 08:22:59 weewx[19] DEBUG user.rtgd: rtgdthread: ****     self.process_packet(_package['payload'])
Aug 30 08:22:59 weewx[19] DEBUG user.rtgd: rtgdthread: ****   File "/home/weewx/bin/user/rtgd.py", line 1805, in process_packet
Aug 30 08:22:59 weewx[19] DEBUG user.rtgd: rtgdthread: ****     cached_packet = self.packet_cache.get_packet(_conv_packet['dateTime'],
Aug 30 08:22:59 weewx[19] DEBUG user.rtgd: rtgdthread: ****   File "/home/weewx/bin/user/rtgd.py", line 2834, in get_packet
Aug 30 08:22:59 weewx[19] DEBUG user.rtgd: rtgdthread: ****     packet[obs] = self.get_value(obs, ts, max_age)
Aug 30 08:22:59 weewx[19] DEBUG user.rtgd: rtgdthread: ****   File "/home/weewx/bin/user/rtgd.py", line 2820, in get_value
Aug 30 08:22:59 weewx[19] DEBUG user.rtgd: rtgdthread: ****     if obs in self.cache and ts - self.cache[obs]['ts'] <= max_age:
Aug 30 08:22:59 weewx[19] DEBUG user.rtgd: rtgdthread: **** TypeError: '<=' not supported between instances of 'int' and 'str'
Aug 30 08:22:59 weewx[19] CRITICAL user.rtgd: Thread exiting. Reason: '<=' not supported between instances of 'int' and 'str'
Aug 30 08:23:03 weewx[19] WARNING user.weatherlink_live: No data since 1 iterations
```

**Comment by selectSt4r** [comment] 2021-08-30 11:42
This looks like an issue:  `thsw:7:appTemp`
Why not set this to `thsw:7`?

**Comment by michael-slx** [comment] 2021-08-30 12:52
Sorry @LMSSonos for the late response.

The [first crash](https://github.com/michael-slx/weewx-weatherlink-live/issues/7#issuecomment-907266675) you posted is related to using the new `battery` mapping option with an old version. Updating to [v1.0.10](https://github.com/michael-slx/weewx-weatherlink-live/releases/tag/v1.0.10) should solve that issue. (Though it seems you've already done that in the meantime.)

The [second crash](https://github.com/michael-slx/weewx-weatherlink-live/issues/7#issuecomment-908067252) seems totally unrelated to this driver and is probably caused by the `rtgd` _(realtime gauge-data)_ extension. Try uninstalling the extension and see if the problem still persists.

**Comment by LMSSonos** [comment] 2021-08-30 13:18
@michael-slx Thanks for the reply

The first one disappeard works also with following config, I assume this is ok with 1.0.10.

`mapping = th:7, th_indoor, baro, rain:7, wind:7, uv:7, solar:7, thw:7, thsw:7:appTemp, windchill:7, battery:7:outTemp:rain:wind:uv` 

Is this valid for the battery? The thing is that in the data `batterStatus1`, `uvBatteryStatus` etc is always 0.

Does not output any error. Sorry for the rtgd issue, this was something else I was testing - sorry for that!

**Comment by michael-slx** [comment] 2021-08-30 13:26
Yes, your config looks fine, assuming your sensor is transmitting on id 7.

Is the battery actually low? `0` means OK, `1` means battery low.

**Comment by LMSSonos** [comment] 2021-08-30 18:57
@michael-slx - thanks for the info, I was expecting a voltage value, that's why I thought 0 is not good ;-) Thanks for clarification.

**Comment by michael-slx** [comment] 2021-08-30 19:00
No problem @LMSSonos
I'll close this issue for now

**Closed as completed by michael-slx** 2021-08-30 19:00 UTC
